export const GET_MINER_STATS_START = "GET_MINER_STATS_START";
export const GET_MINER_STATS_SUCCESS = "GET_MINER_STATS_SUCESS";
export const GET_MINER_STATS_FAIL = "GET_MINER_STATS_FAIL";

export const GET_PAYMENTS_PAGE_START = "GET_PAYMENTS_PAGE_START";
export const GET_PAYMENTS_PAGE_SUCCESS = "GET_PAYMENTS_PAGE_SUCCESS";
export const GET_PAYMENTS_PAGE_FAIL = "GET_PAYMENTS_PAGE_FAIL";

export const GET_MINERS_PAGE_START = "GET_MINERS_PAGE_START";
export const GET_MINERS_PAGE_SUCCESS = "GET_MINERS_PAGE_SUCCESS";
export const GET_MINERS_PAGE_FAIL = "GET_MINERS_PAGE_FAIL";
