export const GET_MINER_DETAILS_START = "GET_MINER_DETAILS_START";
export const GET_MINER_DETAILS_SUCCESS = "GET_MINER_DETAILS_SUCESS";
export const GET_MINER_DETAILS_FAIL = "GET_MINER_DETAILS_FAIL";
export const GET_MINER_PAYMENTS_PAGE_START = "GET_MINER_PAYMENTS_PAGE_START";
export const GET_MINER_PAYMENTS_PAGE_SUCCESS = "GET_MINER_PAYMENTS_PAGE_SUCESS";
export const GET_MINER_PAYMENTS_PAGE_FAIL = "GET_MINER_PAYMENTS_PAGE_FAIL";
